GET http://localhost:7000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imhhbm5haEBoYW5uYWgiLCJpYXQiOjE1MTI2MDU4ODksImV4cCI6MTUxMzIxMDY4OSwic3ViIjoiNWEyODg4YzAzMmI0MDcxZGE1NDY5NDkxIn0.cksHcSInP2802-CHf4eGVHLnWqgsqPKltUtE-4uk5T0

###
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "hannah@hannah",
  "firstName": "Hannah",
  "lastName": "Peters",
  "password": "123456"
}

### 
POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "hannah24@gmail.com",
  "password": "password123"
}